language: cpp
compiler:
  - gcc
env:
  - CXX_VERSION=4.7
before_install:
# g++ 4.7/4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# thrift 0.9.0
  - sudo add-apt-repository -y ppa:fcitx-team/nightly
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo apt-get update
  - sudo apt-get install -y g++-${CXX_VERSION} autoconf-archive libleveldb-dev libsnappy-dev libevent-dev python-support libfuse-dev libattr1-dev scons
  - sudo apt-get install -y libboost1.53-dev libboost-filesystem1.53-dev libboost-system1.53-dev libboost-thread1.53-dev
  - sudo apt-get install -y libgflags-dev libgoogle-glog-dev protobuf-compiler libprotobuf-dev libmysql++-dev libopenmpi1.5-dev
  - export CXX="g++-${CXX_VERSION}"
  - sudo pip install -r requirements.txt
  - wget http://archive.apache.org/dist/thrift/0.9.0/thrift-0.9.0.tar.gz
  - tar -xzf thrift-*.tar.gz
  - cd thrift-*
  - ./configure --without-c_glib --without-java --without-csharp --without-php --without-python --without-ruby --without-erlang --without-qt
  - make && sudo make install
  - cd ..
before_script:
  - echo 'localhost' > nodes.txt
  - ./bootstrap
script:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - export CXXFLAGS=`mpicc --showme:compile`
  - export LDFLAGS=`mpicc --showme:link`
  - ./configure && make
notifications:
  email: false
