#!/bin/sh -
#
# Re-generate ./configure and Makefile.in files.
#
# Copyright 2013 (c) Lei Xu <eddyxu@gmail.com>

case `uname` in
	Darwin*) glibtoolize --copy ;;  # For MacOSX
    *) libtoolize --copy ;; # Otherwise.
esac

autoheader
aclocal -I m4 --install
autoconf

automake --foreign --add-missing --force-missing --copy

git submodule init
git submodule update

if [ ! -d lib/vsfs ]; then
#	git clone https://github.com/vsfs/vsfs.git lib/vsfs
	git clone git@github.com:eddyxu/vsfs.git lib/vsfs
else
	cd lib/vsfs
	git co master
	git pull
	cd -
fi

cd lib/vsfs
./bootstrap
./configure
make
